# Generated by Django 4.1.6 on 2023-04-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
