# Generated by Django 4.1.6 on 2023-02-07 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
