# Generated by Django 4.1.6 on 2023-04-10 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
